### PR TITLE
Create animalfact.js

### PR DESCRIPTION
**Pull request by SirEpiclyAmazing**

### CODE REVIEW

**Comment by anondev-sudo** [comment]
Have you tested it? Before you submit PR, please test it and send screenshot.

**Comment by SirEpiclyAmazing** [comment]
I haven't tested it, but it will work as I just used the animal.js as a template.

**Comment by anondev-sudo** [comment]
its not good, forgot to change command name, description and so.
Also 			`category: "images",` is missing

**Comment by SirEpiclyAmazing** [comment]
i'll fix it

**Comment by SirEpiclyAmazing** [comment]
fixed

**Comment by anondev-sudo** [comment]
Read documentation, the same animals are not for facts and images

**Comment by anondev-sudo** [comment]
image
image

**Comment by SirEpiclyAmazing** [comment]
will fix

**Comment by SirEpiclyAmazing** [comment]
should work now

**Comment by anondev-sudo** [comment]
Not there

**Review by anondev-sudo — APPROVED** [review]

**Pull request merged**
